# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gateway
  namespace: default
  labels:
    app:  gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  gateway
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  gateway
        image:  spring2go/spring-petclinic-cloud-gateway:1.0.0.RELEASE
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        envFrom:
        - configMapRef:
            name: msa-config
        ports:
        - containerPort:  8080
          name:  gateway
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - name: gateway
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001
---
