# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  webapp
  namespace: default
  labels:
    app:  webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  webapp
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  webapp
        image:  spring2go/spring-petclinic-web-app:1.0.0.RELEASE
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        envFrom:
        - configMapRef: 
            name: msa-config
        ports:
        - containerPort:  8081
          name:  webapp
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: default
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - name: webapp
    protocol: TCP
    port: 8080
    targetPort: 8081
    nodePort: 30002
---
