# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vets
  namespace: default
  labels:
    app:  vets
spec:
  selector:
    matchLabels:
      app: vets
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  vets
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  vets
        image:  spring2go/spring-petclinic-vets-service:1.0.0.RELEASE
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 400m
            memory: 400Mi
        envFrom:
        - configMapRef: 
            name: msa-config
        ports:
        - containerPort:  8082
          name:  vets
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: vets
  namespace: default
spec:
  selector:
    app: vets
  type: ClusterIP
  ports:
  - name: vets
    protocol: TCP
    port: 8080
    targetPort: 8082
---
